# Generated by Django 5.0.2 on 2024-04-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoisaParaFazer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.URLField(max_length=2000)),
                ('numero', models.IntegerField()),
                ('descricao', models.TextField()),
                ('tempo', models.FloatField()),
                ('energia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Coisa para fazer',
                'verbose_name_plural': 'Coisas para fazer',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=2000)),
                ('endereco', models.CharField(max_length=300)),
                ('custo', models.FloatField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdaaline.coisaparafazer')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
    ]
